// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Carrega .env local (Render já define env vars diretamente)
try { require('dotenv/config') } catch {}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
